OnlineAccountDemo/Models/Sales.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OnlineAccountDemo.Models

{
    public class Sales
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Required]
        public int BrandId { get; set; }
        [Required]
        public int ModelId { get; set; }
        [Required]
        public int Colorid { get; set; }
        [Required]
        public int EmpId { get; set; }

        [Required]
        public int StorageId { get; set; }
        [Required]
        public double Rate { get; set; }
        [Required]
        public int Quantity { get; set; }
        [Required]
        public double Total { get; set; }
        [Required]
        public string IMEINumber { get; set; }
        [Required]
        public string InvoiceNum { get; set; }
        [Required]
        public string Remarks { get; set; }
        [Required]
        public string PaymentMode { get; set; }
        public bool Deleted { get; set; } = false;
        public bool Status { get; set; } = true;
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }

        public DateTime CreatedDate { get; set; } = DateTime.Now;
        public DateTime UpdatedDate { get; set; } = DateTime.Now;

        public BrandCategory BrandCategory { get; set; }
        public ModelColor ModelColor { get; set; }
        public Employees Employees { get; set; }
        public StorageCapacity StorageCapacity { get; set; }

    }


}

OnlineAccountDemo/Controllers/SalesController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineAccountDemo.Data;
using OnlineAccountDemo.Models;
using OnlineAccountDemo.Helper;
using OnlineAccountDemo.CustomAttributes;
using OnlineAccountDemo.ViewModels;
using Microsoft.EntityFrameworkCore;
using System.Drawing.Imaging;

namespace OnlineAccountDemo.Controllers
{
    [GeneralAuthorization]
    public class SalesController : Controller
    {
        //private Employee empData;
        private readonly ApplicationDbContext _db;
        private Users _ActiveUser => SessionService.GetSession(HttpContext);
        public SalesController(ApplicationDbContext db) : base()
        {
            _db = db;

        }

        [UserAuthorization]
        [HttpPost]
        public IActionResult CreateSales(Sales model_)
        {
            Sales _Sales = new Sales();
            _Sales.BrandId = model_.BrandId;
            _Sales.ModelId = model_.ModelId;
            _Sales.Colorid = model_.Colorid;
            _Sales.StorageId = model_.StorageId;
            _Sales.Quantity = model_.Quantity;
            _Sales.Rate = model_.Rate;
            _Sales.Total = model_.Total;
            _Sales.PaymentMode = model_.PaymentMode;
            _Sales.Remarks = model_.Remarks;
            _Sales.EmpId = model_.EmpId;
            _Sales.InvoiceNum = model_.InvoiceNum;
            _Sales.IMEINumber = model_.IMEINumber;
            _Sales.Status = true;
            _Sales.Deleted = false;
            _Sales.CreatedBy = _ActiveUser.Name;
            _Sales.UpdatedBy = _ActiveUser.Name;

            _db.Sales.Add(_Sales);
            _db.SaveChanges();
            return RedirectToAction("ListSales");
        }

        [UserAuthorization]
        [HttpGet]
        public IActionResult CreateSales()
        {
            ViewBag.EmployeesList = _db.Employees.Where(s => s.Status).ToList();
            ViewBag.ModelColor = _db.ModelColor.Where(s => s.Status).ToList();
            ViewBag.BrandList = _db.BrandCategory.Where(s => s.Status).ToList();
            ViewBag.ModelList = _db.BrandModel.Where(s => s.Status).ToList();
            ViewBag.StorageList = _db.StorageCapacity.Where(s => s.Status).ToList();
            return View();
        }

        [UserAuthorization]
        [HttpGet]
        public IActionResult ListSales()
        {
            // List<Sales> empList = _db.Sales.ToList();
            ViewBag.ModelList = _db.BrandModel.ToList();
            List<Sales> sales = _db.Sales.Where(x=>x.Status && !x.Deleted)
    .Include(ra => ra.BrandCategory)
    .Include(ra => ra.ModelColor)
    .Include(ra => ra.Employees)
    .ToList();
            return View(sales);
        }

        [UserAuthorization]
        [HttpGet]
        public IActionResult SalesReport()
        {
            ViewBag.ModelList = _db.BrandModel.Where(x => x.Status).ToList();
            ViewBag.BrandList = _db.BrandCategory.Where(x => x.Status).ToList();
            ViewBag.IssuesList = _db.ModelIssues.Where(x => x.Status).ToList();
            ViewBag.StorageList = _db.StorageCapacity.Where(s => s.Status).ToList();

            List<Sales> sales = _db.Sales
                .Include(ra => ra.BrandCategory)
                .Include(ra => ra.ModelColor)
                .Include(ra => ra.Employees)
                .ToList();
            ViewBag.SalesList = sales;

            return View(sales);
        }


        [UserAuthorization]
        [HttpGet]
        public IActionResult UpdateSales(int? id)
        {
            ViewBag.EmployeesList = _db.Employees.Where(s => s.Status).ToList();
            ViewBag.StorageList = _db.StorageCapacity.Where(s => s.Status).ToList();
            ViewBag.ModelColor = _db.ModelColor.Where(s => s.Status).ToList();
            ViewBag.BrandList = _db.BrandCategory.Where(s => s.Status).ToList();
            ViewBag.ModelList = _db.BrandModel.Where(s => s.Status).ToList();

            Sales? _Sales = _db.Sales.Where(x => x.Id == id)
                .FirstOrDefault();

            return View(_Sales);
        }

        [UserAuthorization]
        [HttpPost]
        public IActionResult UpdateSales(Sales _tran)
        {
            Sales? _Sales = _db.Sales.Where(x => x.Id == _tran.Id)
              .FirstOrDefault();

            _Sales!.BrandId = _tran.BrandId;
            _Sales.ModelId = _tran.ModelId;
            _Sales.Colorid = _tran.Colorid;
            _Sales.EmpId = _tran.EmpId;
            _Sales.IMEINumber = _tran.IMEINumber;
            _Sales.Quantity = _tran.Quantity;
            _Sales.Rate = _tran.Rate;
            _Sales.Total = _tran.Total;
            _Sales.PaymentMode = _tran.PaymentMode;
            _Sales.Remarks = _tran.Remarks;
            _Sales.InvoiceNum = _tran.InvoiceNum;
            _Sales.UpdatedBy = _ActiveUser.Name;
            _Sales.UpdatedDate = DateTime.Now;
            _db.Sales.Update(_Sales);
            _db.SaveChanges();
            return RedirectToAction("ListSales");
        }


        [UserAuthorization]
        [HttpGet]
        public IActionResult DeleteSales(int? id)
        {
            ViewBag.EmployeesList = _db.Employees.Where(s => s.Status).ToList();
            ViewBag.ModelColor = _db.ModelColor.Where(s => s.Status).ToList();
            ViewBag.BrandList = _db.BrandCategory.Where(s => s.Status).ToList();
            ViewBag.ModelList = _db.BrandModel.Where(s => s.Status).ToList();
            ViewBag.StatusList = _db.JobStatus.Where(s => s.Status).ToList();
            ViewBag.PriceList = _db.IssuePricing.Where(s => s.Status).ToList();
            //todo: Have to implement INITCOMMON For ViewBag LISTS
            Sales? _Sales = _db.Sales.Where(x => x.Id == id)
                .FirstOrDefault();

            return View(_Sales);
        }


        [UserAuthorization]
        [HttpPost]
        public IActionResult DeleteSales(Sales _tran)
        {
            Sales? _Sales = _db.Sales.Where(x => x.Id == _tran.Id)
              .FirstOrDefault();

            _Sales!.Status = false;
            _Sales.Deleted = true;
            _Sales.UpdatedBy = _ActiveUser.Name;
            _Sales.UpdatedDate = DateTime.Now;
            _db.Sales.Update(_Sales);
            _db.SaveChanges();
            return RedirectToAction("ListSales");
        }

    }
}

OnlineAccountDemo/Views/Sales/CreateSales.cshtml
@using OnlineAccountDemo.Models;

@{
    ViewData["Title"] = "Add Sales";
    Layout = "~/Views/Shared/_ISMLayout.cshtml";

    var employeesList = ViewBag.EmployeesList as List<Employees>;
    var issuesList = ViewBag.IssuesList as List<ModelIssues>;
    var colorList = ViewBag.ModelColor as List<ModelColor>;
    var storageList = ViewBag.StorageList as List<StorageCapacity>;
    var brandList = ViewBag.BrandList as List<BrandCategory>;
    var modelList = ViewBag.ModelList as List<BrandModel>;
}

<div class="container">

    @using (Html.BeginForm("CreateSales", "Sales", FormMethod.Post, new { @class = "w-50" }))
    {

        <div class="mb-3">
            <label for="InvoiceNum" class="form-label">Invoice Number</label>
            <input type="text" class="form-control" name="InvoiceNum" placeholder="Enter Invoice Number">
        </div>
        <div class="mb-3">
            <label for="BrandId" class="form-label">Brand</label>
            @Html.DropDownList("BrandId", new SelectList(brandList, "Id", "BrandTitle"),"Select Brand",new { @class = "form-control" })
        </div>

        <div class="mb-3">
            <label for="ModelId" class="form-label">Model</label>
            @Html.DropDownList("ModelId", new SelectList(modelList, "Id", "ModelTitle"),"Select Model",new { @class = "form-control" })
        </div>
        <div class="mb-3">
            <label for="IMEINumber" class="form-label">IEMI Number</label>
            <input type="text" class="form-control" name="IMEINumber" placeholder="Enter IMEI Number">
        </div>
        <div class="mb-3">
            <label for="StorageId" class="form-label">Storage</label>
            @Html.DropDownList("StorageId", new SelectList(storageList, "Id", "StorageTitle"), "Select Storage", new { @class = "form-control" })
        </div>
        <div class="mb-3">
            <label for="Colorid" class="form-label">Color</label>
            @Html.DropDownList("Colorid", new SelectList(colorList, "Id", "ColorTitle"),"Select Color",new { @class = "form-control" })
        </div>
        <div class="mb-3">
            <label for="Quantity" class="form-label">Quantity</label>
            <input type="number" class="form-control" name="Quantity" placeholder="Enter Quantity">
        </div>
        <div class="mb-3">
            <label for="Rate" class="form-label">Rate</label>
            <input type="number" class="form-control" name="Rate" placeholder="Enter Rate">
        </div>
        <div class="mb-3">
            <label for="Total" class="form-label">Total</label>
            <input type="number" class="form-control" name="Total" placeholder="Enter Total">
        </div>
        <div class="mb-3">
            <label for="PaymentMode" class="form-label">Payment Mode</label>
            <input type="text" class="form-control" name="PaymentMode" placeholder="Enter Payment Mode">
        </div>
        <div class="mb-3">
            <label for="EmpId" class="form-label">Sold By</label>
            @Html.DropDownList("EmpId", new SelectList(employeesList, "Id", "EmpName"),"Select Employee",new { @class = "form-control" })
        </div>

        <div class="mb-3">
            <label for="Remarks" class="form-label">Remarks</label>
            <textarea class="form-control" style="height: 100px" name="Remarks"></textarea>
        </div>
@*        <div class="mb-3">
            <label for="BrandCode" class="form-label">Price</label>
            <input type="number" class="form-control" name="Price" placeholder="">
        </div>
*@
        <button type="submit" class="btn btn-primary">Submit</button>
    }

</div>




@section Scripts {

}

OnlineAccountDemo/Views/Sales/DeleteSales.cshtml
@using OnlineAccountDemo.Models;
@model OnlineAccountDemo.Models.Sales;

@{
    ViewData["Title"] = "Delete Sales";
    Layout = "~/Views/Shared/_ISMLayout.cshtml";

    int selectedBrandId = Model.BrandId;
    int selectedModelId = Model.ModelId;
    int selectedColorId = Model.Colorid;
    int selectedEmpId = Model.EmpId;

    var employeesList = ViewBag.EmployeesList as List<Employees>;
    var colorList = ViewBag.ModelColor as List<ModelColor>;
    var brandList = ViewBag.BrandList as List<BrandCategory>;
    var modelList = ViewBag.ModelList as List<BrandModel>;
}

<div class="container">

    @using (Html.BeginForm("DeleteSales", "Sales", FormMethod.Post, new { @class = "w-50" }))
    {
        <div class="mb-3">
            <label for="BrandId" class="form-label">Brand</label>
            @Html.DropDownList("BrandId", new SelectList(brandList, "Id", "BrandTitle",selectedBrandId),"Select Brand",new { @class = "form-control", @readonly="readonly"})
        </div>
        <div class="mb-3">
            <label for="ModelId" class="form-label">Model</label>
            @Html.DropDownList("ModelId", new SelectList(modelList, "Id", "ModelTitle",selectedModelId),"Select Model",new { @class = "form-control" , @readonly="readonly"})
        </div>
        <div class="mb-3">
            <label for="BrandCode" class="form-label">IEMI Number</label>
            <input type="text" class="form-control" name="IMEINumber" value="@Model.IMEINumber" readonly>
        </div>

        <div class="mb-3">
            <label for="Colorid" class="form-label">Color</label>
            @Html.DropDownList("Colorid", new SelectList(colorList, "Id", "ColorTitle",selectedColorId),"Select Color",new { @class = "form-control", @readonly="readonly" })
        </div>

        <div class="mb-3">
            <label for="EmpId" class="form-label">Employee</label>
            @Html.DropDownList("EmpId", new SelectList(employeesList, "Id", "EmpName",selectedEmpId),"Select Employee",new { @class = "form-control" , @readonly="readonly"})
        </div>

@*        <div class="mb-3">
            <label for="BrandCode" class="form-label">Price</label>
            <input type="number" class="form-control" name="Price" placeholder="">
        </div>
*@
        <button type="submit" class="btn btn-danger">Delete</button>
    }

</div>




@section Scripts {

}

OnlineAccountDemo/Views/Sales/ListSales.cshtml
@model IEnumerable<OnlineAccountDemo.Models.Sales>
@using OnlineAccountDemo.Models;

@{
    ViewData["Title"] = "List Sales";
    Layout = "~/Views/Shared/_ISMLayout.cshtml";

    var brandModelList = ViewBag.ModelList as List<BrandModel>;
}


<div class="container">
    <a href="@Url.Action("CreateSales","Sales")" class="btn btn-outline-success btn-lg bx-pull-right"><i class="bx bx-plus-medical"></i></a>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">Model</th>
                <th scope="col">IMEI Number</th>
                <th scope="col">Color</th>
                <th scope="col">Quantity</th>
                <th scope="col">Employee</th>
                <th scope="col">Remarks</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var _brands in Model.GroupBy(x => x.BrandId))
            {
                <tr>
                    <td colspan="9"><h4><span class="badge bg-dark">@_brands.Select(x=>x.BrandCategory.BrandTitle).FirstOrDefault()</span></h4></td>
                </tr>

                @*                foreach (var _models in item.GroupBy(x => x.ModelId))
            {*@
                foreach (var item in _brands.OrderBy(x => x.ModelId))
                {
                    <tr>
                        <td>@brandModelList!.Where(x => x.Id == item.ModelId).Select(x => x.ModelTitle).FirstOrDefault()</td>
                        <td>@item.IMEINumber</td>
                        <td>@item.ModelColor.ColorTitle</td>
                        <td>@item.Quantity</td>
                        <td>@item.Employees.EmpName</td>
                        <td>@item.Remarks</td>
                        <td>
                            <a class="btn btn-outline-primary btn-sm" href="@Url.Action("UpdateSales", new { id=item.Id})"><i class="bi bi-box-arrow-up"></i></a>
                            <a class="btn btn-outline-danger btn-sm" href="@Url.Action("DeleteSales", new { id=item.Id})"><i class="bx bx-minus-circle"></i></a>
                        </td>
                    </tr>
                }

                @*   }*@



            }

        </tbody>
    </table>
</div>


@section Scripts {

}

OnlineAccountDemo/Views/Sales/SalesReport.cshtml
@model IEnumerable<OnlineAccountDemo.Models.Sales>
@using OnlineAccountDemo.Models;

@{
    ViewData["Title"] = "Sales Report";
    Layout = "~/Views/Shared/_ISMLayout.cshtml";

    var brandModelList = ViewBag.ModelList as List<BrandModel>;
    var _issuesList = ViewBag.IssuesList as List<ModelIssues>;
}



<div class="container">
   @*  <table class="table">
        <thead>
            <tr>
                <th></th>

            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model.GroupBy(x => x.BrandId))
            {
                <tr>
                    <td colspan="4"><h3>@item.Select(x=>x.BrandCategory.BrandTitle).FirstOrDefault() </h3></td>

                </tr>
                foreach (var _issues in item.GroupBy(x => x.IssueId))
                {
                    <tr>
                        <td>
                            <h4><span class="badge bg-success">@_issuesList!.Where(x=>x.Id==_issues.Key).Select(x=>x.IssueTitle).FirstOrDefault()</span></h4>
                        </td>
                    </tr>
                    <tr>
                        <th>Model</th>
                        <th>Quantity</th>
                    </tr>

                    foreach (var _models in _issues.GroupBy(x => x.ModelId))
                    {

                        var _count = (decimal)_models.Where(x => x.IssueId == _issues.Key).Count();
                        <tr>
                            <td>@brandModelList!.Where(x=>x.Id==_models.Key).Select(x=>x.ModelTitle).FirstOrDefault()</td>
                        </tr>
                    }
                }

            }
        </tbody>
    </table> *@
</div>

@section Scripts {

}

OnlineAccountDemo/Views/Sales/UpdateSales.cshtml
@using OnlineAccountDemo.Models;
@{
    ViewData["Title"] = "Edit Sales";
    Layout = "~/Views/Shared/_ISMLayout.cshtml";

    int selectedBrandId = Model.BrandId;
    int selectedModelId = Model.ModelId;
    int selectedColorId = Model.Colorid;
    int selectedEmpId = Model.EmpId;

    var employeesList = ViewBag.EmployeesList as List<Employees>;
    var colorList = ViewBag.ModelColor as List<ModelColor>;
    var brandList = ViewBag.BrandList as List<BrandCategory>;
    var modelList = ViewBag.ModelList as List<BrandModel>;
}

<div class="container">

    @using (Html.BeginForm("UpdateSales", "Sales", FormMethod.Post, new { @class = "w-50" }))
    {
        <div class="mb-3">
            <label for="InvoiceNum" class="form-label">Invoice Number</label>
            <input type="text" class="form-control" name="InvoiceNum" value="@Model.InvoiceNum">
        </div>
        <div class="mb-3">
            <label for="BrandId" class="form-label">Brand</label>
            @Html.DropDownList("BrandId", new SelectList(brandList, "Id", "BrandTitle",selectedBrandId),"Select Brand",new { @class = "form-control" })
        </div>
        <div class="mb-3">
            <label for="ModelId" class="form-label">Model</label>
            @Html.DropDownList("ModelId", new SelectList(modelList, "Id", "ModelTitle",selectedModelId),"Select Model",new { @class = "form-control" })
        </div>
        <div class="mb-3">
            <label for="BrandCode" class="form-label">IEMI Number</label>
            <input type="text" class="form-control" name="IMEINumber" value="@Model.IMEINumber">
        </div>

        <div class="mb-3">
            <label for="Colorid" class="form-label">Color</label>
            @Html.DropDownList("Colorid", new SelectList(colorList, "Id", "ColorTitle",selectedColorId),"Select Color",new { @class = "form-control" })
        </div>

        <div class="mb-3">
            <label for="Quantity" class="form-label">Quantity</label>
            <input type="number" class="form-control" name="Quantity" value="@Model.Quantity">
        </div>
        <div class="mb-3">
            <label for="Rate" class="form-label">Rate</label>
            <input type="number" class="form-control" name="Rate" value="@Model.Rate">
        </div>
        <div class="mb-3">
            <label for="Total" class="form-label">Total</label>
            <input type="number" class="form-control" name="Total" value="@Model.Total">
        </div>
        <div class="mb-3">
            <label for="PaymentMode" class="form-label">Payment Mode</label>
            <input type="text" class="form-control" name="PaymentMode" value="@Model.PaymentMode">
        </div>

        <div class="mb-3">
            <label for="EmpId" class="form-label">Sold By</label>
            @Html.DropDownList("EmpId", new SelectList(employeesList, "Id", "EmpName",selectedEmpId),"Select Employee",new { @class = "form-control" })
        </div>
        <div class="mb-3">
            <label for="Remarks" class="form-label">Remarks</label>
            <textarea class="form-control" style="height: 100px" name="Remarks" value="@Model.Remarks">@Model.Remarks</textarea>
        </div>

        <button type="submit" class="btn btn-primary">Update</button>
    }

</div>




@section Scripts {

}