OnlineAccountDemo/Controllers/IssuesPricingController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineAccountDemo.Data;
using OnlineAccountDemo.Models;
using OnlineAccountDemo.Helper;
using OnlineAccountDemo.CustomAttributes;
using OnlineAccountDemo.ViewModels;
using Microsoft.EntityFrameworkCore;
using System.Drawing.Imaging;

namespace OnlineAccountDemo.Controllers
{
    [GeneralAuthorization]
    public class IssuesPricingController : Controller
    {
        //private priceloyee priceData;
        private readonly ApplicationDbContext _db;
        private Users _ActiveUser => SessionService.GetSession(HttpContext);
        public IssuesPricingController(ApplicationDbContext db) : base()
        {
            _db = db;

        }

        [UserAuthorization]
        [HttpPost]
            public IActionResult CreatePricing(IssuePricing model_)
        {
            IssuePricing pricing_model = new IssuePricing();
            pricing_model.IssueModelId = model_.IssueModelId;
            pricing_model.IssueBrandId = model_.IssueBrandId;
            pricing_model.IssuesId = model_.IssuesId;
            pricing_model.IssuePrice = model_.IssuePrice;
            pricing_model.Status = true;
            pricing_model.Deleted = false;
            pricing_model.CreatedBy = _ActiveUser.Name;
            pricing_model.UpdatedBy = _ActiveUser.Name;

            _db.IssuePricing.Add(pricing_model);
            _db.SaveChanges();
            return RedirectToAction("ListIssuesPricing");
        }

        [UserAuthorization]
        [HttpGet]
        public IActionResult CreatePricing()
        {
            ViewBag.ModelList = _db.BrandModel.Where(s => s.Status).ToList();
            ViewBag.BrandList = _db.BrandCategory.Where(s => s.Status).ToList();
            ViewBag.IssuesList = _db.ModelIssues.Where(s => s.Status).ToList();

            return View();
        }

        [UserAuthorization]
        [HttpGet]
        public IActionResult ListIssuesPricing()
        {
            ViewBag.ModelList = _db.BrandModel.Where(s => s.Status).ToList();
            ViewBag.BrandList = _db.BrandCategory.Where(s => s.Status).ToList();
            ViewBag.IssuesList = _db.ModelIssues.Where(s => s.Status).ToList();
            List<IssuePricing> priceList = _db.IssuePricing.Where(x=>x.Status).ToList();
            return View(priceList);
        }


        [UserAuthorization]
        [HttpGet]
        public IActionResult UpdatePricing(int? id)
        {
            ViewBag.ModelList = _db.BrandModel.Where(s => s.Status).ToList();
            ViewBag.BrandList = _db.BrandCategory.Where(s => s.Status).ToList();
            ViewBag.IssuesList = _db.ModelIssues.Where(s => s.Status).ToList();

            IssuePricing? _IssuePricing = _db.IssuePricing.Where(x => x.Id == id)
                .FirstOrDefault();

            return View(_IssuePricing);
        }

        [UserAuthorization]
        [HttpPost]
        public IActionResult UpdatePricing(IssuePricing price)
        {
            ViewBag.ModelList = _db.BrandModel.Where(s => s.Status).ToList();
            ViewBag.BrandList = _db.BrandCategory.Where(s => s.Status).ToList();
            ViewBag.IssuesList = _db.ModelIssues.Where(s => s.Status).ToList();

            IssuePricing? _IssuePricing = _db.IssuePricing.Where(x => x.Id == price.Id)
              .FirstOrDefault();

            _IssuePricing!.IssuesId = price.IssuesId;
            _IssuePricing.IssueBrandId = price.IssueBrandId;
            _IssuePricing.IssuePrice = price.IssuePrice;
            _IssuePricing.IssueModelId = price.IssueModelId;
            _IssuePricing.UpdatedBy = _ActiveUser.Name;
            _IssuePricing.UpdatedDate = DateTime.Now;
            _db.IssuePricing.Update(_IssuePricing);
            _db.SaveChanges();
            return RedirectToAction("ListIssuesPricing");
        }


        [UserAuthorization]
        [HttpGet]
        public IActionResult DeletePricing(int? id)
        {
            ViewBag.ModelList = _db.BrandModel.Where(s=>s.Status).ToList();
            ViewBag.BrandList = _db.BrandCategory.Where(s => s.Status).ToList();
            ViewBag.IssuesList = _db.ModelIssues.Where(s => s.Status).ToList();

            IssuePricing? _IssuePricing = _db.IssuePricing.Where(x => x.Id == id)
                .FirstOrDefault();

            return View(_IssuePricing);
        }


        [UserAuthorization]
        [HttpPost]
        public IActionResult DeletePricing(IssuePricing price)
        {
            IssuePricing? _IssuePricing = _db.IssuePricing.Where(x => x.Id == price.Id)
              .FirstOrDefault();

            _IssuePricing!.Status = false;
            _IssuePricing.Deleted = true;
            _IssuePricing.UpdatedBy = _ActiveUser.Name;
            _IssuePricing.UpdatedDate = DateTime.Now;
            _db.IssuePricing.Update(_IssuePricing);
            _db.SaveChanges();
            return RedirectToAction("ListIssuesPricing");
        }

    }
}

OnlineAccountDemo/Views/IssuesPricing/CreatePricing.cshtml
@using OnlineAccountDemo.Models;

@{
    ViewData["Title"] = "Add Price";
    Layout = "~/Views/Shared/_ISMLayout.cshtml";


    var issuesList = ViewBag.IssuesList as List<ModelIssues>;
    var brandList = ViewBag.BrandList as List<BrandCategory>;
    var modelList = ViewBag.ModelList as List<BrandModel>;
}

<div class="container mt-5">
    
    @using (Html.BeginForm("CreatePricing", "IssuesPricing", FormMethod.Post, new { @class = "w-100" }))
    {

        <div class="mb-3">
            <label for="BrandId" class="form-label">Brand</label>
            @Html.DropDownList("IssueBrandId", new SelectList(brandList, "Id", "BrandTitle"),"Select Brand",new { @class = "form-control" })
        </div>
            <div class="mb-3">
            <label for="ModelId" class="form-label">Model</label>
            @Html.DropDownList("IssueModelId", new SelectList(modelList, "Id", "ModelTitle"),"Select Model",new { @class = "form-control" })
            </div>
            <div class="mb-3">
            <label for="IssuesId" class="form-label">Issue</label>
            @Html.DropDownList("IssuesId", new SelectList(issuesList, "Id", "IssueTitle"),"Select Issue",new { @class = "form-control" })
            </div>

            <div class="mb-3">
            <label for="IssuePrice" class="form-label">Price</label>
            <input type="number" class="form-control" name="IssuePrice" placeholder="">
            </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    }

</div>




 @section Scripts {

}

OnlineAccountDemo/Views/IssuesPricing/DeletePricing.cshtml
@using OnlineAccountDemo.Models;
@model OnlineAccountDemo.Models.IssuePricing;

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_ISMLayout.cshtml";

    int selectedBrandId = Model.IssueBrandId;
    int selectedModelId = Model.IssueModelId;
    int selectedIssueId = Model.IssuesId;

    var issuesList = ViewBag.IssuesList as List<ModelIssues>;
    var brandList = ViewBag.BrandList as List<BrandCategory>;
    var modelList = ViewBag.ModelList as List<BrandModel>;
}

<div class="container mt-5">
    
    @using (Html.BeginForm("DeletePricing", "IssuesPricing", FormMethod.Post, new { @class = "w-100" }))
    {

        <div class="mb-3">
            <label for="BrandId" class="form-label">Brand</label>
            @Html.DropDownList("IssueBrandId", new SelectList(brandList, "Id", "BrandTitle",selectedBrandId),"Select Brand",new { @class = "form-control" })
        </div>
            <div class="mb-3">
            <label for="ModelId" class="form-label">Model</label>
            @Html.DropDownList("IssueModelId", new SelectList(modelList, "Id", "ModelTitle",selectedModelId),"Select Model",new { @class = "form-control" })
            </div>
            <div class="mb-3">
            <label for="IssuesId" class="form-label">Issue</label>
            @Html.DropDownList("IssuesId", new SelectList(issuesList, "Id", "IssueTitle",selectedIssueId),"Select Issue",new { @class = "form-control" })
            </div>

            <div class="mb-3">
            <label for="IssuePrice" class="form-label">Price</label>
            <input type="number" class="form-control" name="IssuePrice" value="@Model.IssuePrice"readonly>
            </div>
    <button type="submit" class="btn btn-danger">Delete</button>
    }

</div>




 @section Scripts {

}

OnlineAccountDemo/Views/IssuesPricing/ListIssuesPricing.cshtml
@model IEnumerable<OnlineAccountDemo.Models.IssuePricing>
@using OnlineAccountDemo.Models;

@{
    ViewData["Title"] = "Pricing List";
    Layout = "~/Views/Shared/_ISMLayout.cshtml";



    var issuesList = ViewBag.IssuesList as List<ModelIssues>;
    var brandList = ViewBag.BrandList as List<BrandCategory>;
    var modelList = ViewBag.ModelList as List<BrandModel>;
}


<div class="container">
    <a href="@Url.Action("CreatePricing","IssuesPricing")" class="btn btn-outline-success btn-lg bx-pull-right"><i class="bx bx-plus-medical"></i></a>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Brand</th>
                <th scope="col">Model</th>
                <th scope="col">Issue</th>
                <th scope="col">Price</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@brandList!.Where(x=>x.Id==item.IssueBrandId).Select(x=>x.BrandTitle).FirstOrDefault()</td>
                    <td>@modelList!.Where(x=>x.Id==item.IssueModelId).Select(x=>x.ModelTitle).FirstOrDefault()</td>
                    <td>@issuesList!.Where(x=>x.Id==item.IssuesId).Select(x=>x.IssueTitle).FirstOrDefault()</td>
                    <td>@item.IssuePrice</td>
                    <td>
                        <a class="btn btn-outline-primary btn-sm" href="@Url.Action("UpdatePricing", new { id=item.Id})"><i class="bi bi-box-arrow-up"></i></a>
                        <a class="btn btn-outline-danger btn-sm" href="@Url.Action("DeletePricing", new { id=item.Id})"><i class="bx bx-minus-circle"></i></a>
                    </td>
                </tr>
            }

        </tbody>
    </table>
</div>


@section Scripts {

}

OnlineAccountDemo/Views/IssuesPricing/UpdatePricing.cshtml
@using OnlineAccountDemo.Models;
@model OnlineAccountDemo.Models.IssuePricing;

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_ISMLayout.cshtml";

    int selectedBrandId = Model.IssueBrandId;
    int selectedModelId = Model.IssueModelId;
    int selectedIssueId = Model.IssuesId;

    var issuesList = ViewBag.IssuesList as List<ModelIssues>;
    var brandList = ViewBag.BrandList as List<BrandCategory>;
    var modelList = ViewBag.ModelList as List<BrandModel>;
}

<div class="container mt-5">
    
    @using (Html.BeginForm("UpdatePricing", "IssuesPricing", FormMethod.Post, new { @class = "w-100" }))
    {

        <div class="mb-3">
            <label for="BrandId" class="form-label">Brand</label>
            @Html.DropDownList("IssueBrandId", new SelectList(brandList, "Id", "BrandTitle",selectedBrandId),"Select Brand",new { @class = "form-control" })
        </div>
            <div class="mb-3">
            <label for="ModelId" class="form-label">Model</label>
            @Html.DropDownList("IssueModelId", new SelectList(modelList, "Id", "ModelTitle",selectedModelId),"Select Model",new { @class = "form-control" })
            </div>
            <div class="mb-3">
            <label for="IssuesId" class="form-label">Issue</label>
            @Html.DropDownList("IssuesId", new SelectList(issuesList, "Id", "IssueTitle",selectedIssueId),"Select Issue",new { @class = "form-control" })
            </div>

            <div class="mb-3">
            <label for="IssuePrice" class="form-label">Price</label>
            <input type="number" class="form-control" name="IssuePrice" value="@Model.IssuePrice">
            </div>
    <button type="submit" class="btn btn-primary">Update</button>
    }

</div>




 @section Scripts {

}