OnlineAccountDemo/Controllers/UserAccountDetailsController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineAccountDemo.Data;
using OnlineAccountDemo.Models;
using OnlineAccountDemo.Helper;
using OnlineAccountDemo.CustomAttributes;
using OnlineAccountDemo.ViewModels;
using Microsoft.EntityFrameworkCore;

namespace OnlineAccountDemo.Controllers
{
    [GeneralAuthorization]
    public class UserAccountDetailsController : Controller
    {
        //private Employee empData;
        private readonly ApplicationDbContext _db;
        private Users _ActiveUser => SessionService.GetSession(HttpContext);
        public UserAccountDetailsController(ApplicationDbContext db) : base()
        {
            _db = db;

        }
        [UserAuthorization]
        public IActionResult AccountDetails()
        {
           Users? UserAccDetails = _db.Users.Where(x=>x.Id==_ActiveUser.Id).Include(x=>x.UsersAccount).FirstOrDefault();
            UserInfoVM userInfo = new UserInfoVM()
            {
                Id= _ActiveUser.Id,
                Address =UserAccDetails.Address,
                Name =UserAccDetails.Name,
                Email = UserAccDetails.Email,
                AccountNumber = UserAccDetails.UsersAccount.AccountNumber,
                TotalBalance=UserAccDetails.UsersAccount.TotalBalance,
                CreatedDate= UserAccDetails.CreatedDate,
                UpdatedDate= UserAccDetails.UsersAccount.UpdatedDate,
                Status= UserAccDetails.Status
            };
            return View(userInfo);
        }

        public UserInfoVM InitCommon()
        {
            Users? UserAccDetails = _db.Users.Where(x => x.Id == _ActiveUser.Id).Include(x => x.UsersAccount).FirstOrDefault();
            UserInfoVM userInfo = new UserInfoVM()
            {
                Id = _ActiveUser.Id,
                Address = UserAccDetails.Address,
                Name = UserAccDetails.Name,
                Email = UserAccDetails.Email,
                AccountNumber = UserAccDetails.UsersAccount.AccountNumber,
                TotalBalance = UserAccDetails.UsersAccount.TotalBalance,
                CreatedDate = UserAccDetails.CreatedDate,
                UpdatedDate = UserAccDetails.UsersAccount.UpdatedDate,
                Status = UserAccDetails.Status
            };
            return userInfo;
        }


        [HttpGet]
        public IActionResult accDeposit(int id)
        {
            UserInfoVM userInfo = InitCommon();
            return View(userInfo);
        }
        [HttpPost]
            public IActionResult accDeposited(int amt)
        {
            UsersAccount? userAccInfo = _db.UsersAccount.Where(x => x.UserId == _ActiveUser.Id).FirstOrDefault();
            userAccInfo.TotalBalance = userAccInfo.TotalBalance + amt;
            userAccInfo.UpdatedDate = DateTime.Now;
            _db.UsersAccount.Update(userAccInfo);
            _db.SaveChanges();
            return RedirectToAction("AccountDetails");
        }

        [HttpGet]
        public IActionResult accWithdraw(int id)
        {
            UserInfoVM userInfo = InitCommon();
            return View(userInfo);
        }
        [HttpPost]
        public IActionResult accWithdrawal(int amt)
        {
            try
            {
                UsersAccount? userAccInfo = _db.UsersAccount.Where(x => x.UserId == _ActiveUser.Id).FirstOrDefault();
                if (userAccInfo.TotalBalance > amt)
                {
                    userAccInfo.TotalBalance = userAccInfo.TotalBalance - amt;
                    userAccInfo.UpdatedDate = DateTime.Now;
                    _db.UsersAccount.Update(userAccInfo);
                    _db.SaveChanges();
                }
                else
                {
                    throw new Exception("Your Balance is Low");
                }

            }
            catch (Exception ex)
            {
            }

            return RedirectToAction("AccountDetails");
        }
        /* public IActionResult accWithdrawl(Record record, String Type)
         {
             Employee empData = SessionService.GetSession(HttpContext);
             Record value = _db.Records.Find(record.Id);
             value.Task = record.Task;
             _db.SaveChanges();
             if (empData.IsAdmin)
             {
                 return RedirectToAction("Index", "Admin");
             }
             return RedirectToAction("EmployeeTask");
         }
         public IActionResult deleteTask(int taskId)
         {
             Employee empData = SessionService.GetSession(HttpContext);
             Record data = _db.Records.Find(taskId);
             _db.Records.Remove(data);
             _db.SaveChanges();
             if (empData.IsAdmin)
             {
                 return RedirectToAction("Index", "Admin");
             }
             return RedirectToAction("EmployeeTask");

         }*/
    }
}

OnlineAccountDemo/Views/UserAccountDetails/AccountDetails.cshtml
@model OnlineAccountDemo.ViewModels.UserInfoVM

@{
    ViewData["Title"] = "Users";
    Layout = null;
}

<h1>Howdy! @Model.Name</h1>
<a href="@Url.Action("Logout","Login")" class="btn btn-danger">Logout</a>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">

<style>
    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }

    .main-div {
        margin: 100px auto;
        width: 650px;
        border-radius: 5px;
        box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;
    }
</style>

<div class="container mt-5">
    <h2>Details Page</h2>
    <hr />

    <div class="row">
        <div class="col-md-6">
            <dl class="row">

                <dt class="col-sm-3">Address:</dt>
                <dd class="col-sm-9">@Model.Address</dd>

                <dt class="col-sm-3">Account Number:</dt>
                <dd class="col-sm-9">@Model.AccountNumber</dd>

                <dt class="col-sm-3">Total Balance:</dt>
                <dd class="col-sm-9">@Model.TotalBalance</dd>

                <dt class="col-sm-3">Status:</dt>

                @if (Model.Status)
                {
                    <dd class="col-sm-9">Active</dd>
                }
                else
                {
                    <dd class="col-sm-9">Not Active</dd>
                }

            </dl>
        </div>
    </div>

    <a href="@Url.Action("accDeposit","UserAccountDetails", new { id = Model.Id })" class="btn btn-primary">Deposit Amount</a>
    <a href="@Url.Action("accWithdraw","UserAccountDetails", new { id = Model.Id })" class="btn btn-dark">Withdrawl Amount</a>
</div>




 @section Scripts {

}

OnlineAccountDemo/Views/UserAccountDetails/accDeposit.cshtml
@model OnlineAccountDemo.ViewModels.UserInfoVM

@{
    ViewData["Title"] = "Users";
    Layout = null;
}

<h1>Howdy! @Model.Name</h1>
<a href="@Url.Action("Logout","Login")" class="btn btn-danger">Logout</a>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">

<style>
    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }

    .main-div {
        margin: 100px auto;
        width: 650px;
        border-radius: 5px;
        box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;
    }
</style>

<div class="container mt-5">
    <h2>Details Page</h2>
    <hr />

    <div class="row">
        <div class="col-md-6">
            <dl class="row">

                <dt class="col-sm-3">Address:</dt>
                <dd class="col-sm-9">@Model.Address</dd>

                <dt class="col-sm-3">Account Number:</dt>
                <dd class="col-sm-9">@Model.AccountNumber</dd>

                <dt class="col-sm-3">Total Balance:</dt>
                <dd class="col-sm-9">@Model.TotalBalance</dd>

                <dt class="col-sm-3">Status:</dt>

                @if (Model.Status)
                {
                    <dd class="col-sm-9">Active</dd>
                }
                else
                {
                    <dd class="col-sm-9">Not Active</dd>
                }

            </dl>
        </div>
    </div>

  

    @using (Html.BeginForm("accDeposited", "UserAccountDetails", FormMethod.Post, new { @class = "w-100" }))
    {
        <input class="w-50"type="number" name="amt" placeholder="Enter Amount You Want To Deposit">
        <button type="submit" class="btn btn-success w-100">Deposit</button>
    }

</div>




 @section Scripts {
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

<script>

    $(document).ready(function () {


        $("#_deposit").on("click", function () {
            $("#dep").toggle();
        });

        });
</script>
}

OnlineAccountDemo/Views/UserAccountDetails/accWithdraw.cshtml
@model OnlineAccountDemo.ViewModels.UserInfoVM

@{
    ViewData["Title"] = "Users";
    Layout = null;
}

<h1>Howdy! @Model.Name</h1>
<a href="@Url.Action("Logout","Login")" class="btn btn-danger">Logout</a>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">

<style>
    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }

    .main-div {
        margin: 100px auto;
        width: 650px;
        border-radius: 5px;
        box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;
    }
</style>

<div class="container mt-5">
    <h2>Details Page</h2>
    <hr />

    <div class="row">
        <div class="col-md-6">
            <dl class="row">

                <dt class="col-sm-3">Address:</dt>
                <dd class="col-sm-9">@Model.Address</dd>

                <dt class="col-sm-3">Account Number:</dt>
                <dd class="col-sm-9">@Model.AccountNumber</dd>

                <dt class="col-sm-3">Total Balance:</dt>
                <dd class="col-sm-9">@Model.TotalBalance</dd>

                <dt class="col-sm-3">Status:</dt>

                @if (Model.Status)
                {
                    <dd class="col-sm-9">Active</dd>
                }
                else
                {
                    <dd class="col-sm-9">Not Active</dd>
                }

            </dl>
        </div>
    </div>

  

    @using (Html.BeginForm("accWithdrawal", "UserAccountDetails", FormMethod.Post, new { @class = "w-100" }))
    {
        <input class="w-50" type="number" name="amt" placeholder="Enter Amount You Want To Withdraw">
        <button type="submit" class="btn btn-success w-100">Withdraw</button>
    }

</div>




 @section Scripts {

}